apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: map-reduce-
  namespace: playground
spec:
  serviceAccountName: playground-sa
  entrypoint: map-reduce-example
  artifactRepositoryRef: 
    configMap: s3-repo-config
    key: artifactRepository
  arguments:
    parameters:
      - name: numParts
        value: "4"
  onExit: exit-handler
  templates:
  - name: map-reduce-example
    dag:
      tasks:
        - name: split
          template: split
          arguments:
            parameters:
              - name: numParts
                value: "{{workflow.parameters.numParts}}"

        - name: map
          template: map
          arguments:
            parameters:
              - name: partId
                value: "{{item}}"
            artifacts:
              - name: part
                s3:
                  key: "argo/{{workflow.name}}/parts/{{item}}.json"
          depends: "split"
          withParam: "{{tasks.split.outputs.result}}"

        - name: reduce
          template: reduce
          arguments:
            artifacts: 
              - name: results
                s3:
                  key: "argo/{{workflow.name}}/results"
          depends: "map"

  - name: exit-handler
    steps:
    - - name: celebrate
        template: celebrate
        when: "{{workflow.status}} == Succeeded"
    - - name: cry
        template: cry
        when: "{{workflow.status}} != Succeeded"

  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hooray!"]

  - name: cry
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo Ahhhh!"]

  - name: split
    inputs:
      parameters:
        - name: numParts
    script:
      image: python:alpine3.6
      command: 
        - python
      source: |
        import json
        import os
        import sys
        os.mkdir("/mnt/out")
        partIds = list(map(lambda x: str(x), range({{inputs.parameters.numParts}})))
        for i, partId in enumerate(partIds, start=1):
          with open("/mnt/out/" + partId + ".json", "w") as f:
            json.dump({"foo": i}, f)
        json.dump(partIds, sys.stdout)
    outputs:
      artifacts:
      - name: parts
        path: /mnt/out
        archive: 
          none: { }
        s3:
          key: "argo/{{workflow.name}}/parts/"

  - name: map
    inputs:
      parameters:
        - name: partId
      artifacts:
        - name: part
          path: /mnt/in/part.json
    script:
      image: python:alpine3.6
      command: 
        - python
      source: |
        import json
        import os
        import sys
        os.mkdir("/mnt/out")
        with open("/mnt/in/part.json") as f:
            part = json.load(f)
        with open("/mnt/out/part.json", "w") as f:
          json.dump({"bar": part["foo"] * 2}, f)
    outputs:
      artifacts:
      - name: part
        path: /mnt/out/part.json
        archive: 
          none: { }
        s3:
          key: "argo/{{workflow.name}}/results/{{inputs.parameters.partId}}.json"

  - name: reduce
    inputs:
      artifacts:
        - name: results
          path: /mnt/in
    script:
      image: python:alpine3.6
      command:
        - python
      source: |
        import json
        import os
        import sys
        total = 0
        os.mkdir("/mnt/out")
        for f in list(map(lambda x: open("/mnt/in/" + x), os.listdir("/mnt/in"))):
          result = json.load(f)
          total = total + result["bar"]
        with open("/mnt/out/total.json" , "w") as f:
          json.dump({"total": total}, f)
    outputs:
      artifacts:
        - name: total
          path: /mnt/out/total.json
          archive:
            none: { }
          s3:
            key: "argo/{{workflow.name}}/total.json"